import {
  Firestore,
  doc,
  // setDoc, // Not used directly as addDoc generates ID
  getDoc,
  updateDoc,
  deleteDoc,
  collection,
  addDoc,
  getDocs,
  query,
  where,
  serverTimestamp,
  Timestamp,
  orderBy,
} from 'firebase/firestore';
import type { Student } from '@/types';

// Re-export Student type for convenience
export type { Student };

/**
 * Creates a new student profile in Firestore.
 * The 'id' for the student profile will be auto-generated by Firestore.
 * @param db Firestore instance.
 * @param studentData Object containing userId and other student-specific fields.
 *                    It should not include 'id', 'createdAt', or 'updatedAt'.
 * @returns Promise<string> The ID of the newly created student profile.
 */
export const createStudentProfile = async (
  db: Firestore,
  // Explicitly define the expected type for studentData
  studentData: Pick<Student, 'userId' | 'groupId' | 'enrollmentDate' | 'status' | 'studentCardId'>
): Promise<string> => {
  const dataWithTimestamps: Omit<Student, 'id'> = {
    ...studentData,
    // Ensure enrollmentDate is already a Timestamp if passed directly
    // If it's a Date object, it should be converted before calling this function
    // or converted here if this function is designed to accept Date objects.
    // For now, assuming it's passed as a Timestamp from the form.
    createdAt: serverTimestamp() as Timestamp,
    updatedAt: serverTimestamp() as Timestamp,
  };
  const docRef = await addDoc(collection(db, 'students'), dataWithTimestamps);
  return docRef.id;
};

/**
 * Fetches a specific student profile from Firestore by its document ID.
 * @param db Firestore instance.
 * @param studentProfileId The document ID of the student profile.
 * @returns Promise<Student | null> The student profile or null if not found.
 */
export const getStudentProfile = async (
  db: Firestore,
  studentProfileId: string
): Promise<Student | null> => {
  const studentRef = doc(db, 'students', studentProfileId);
  const docSnap = await getDoc(studentRef);
  if (docSnap.exists()) {
    return { id: docSnap.id, ...docSnap.data() } as Student;
  }
  return null;
};

/**
 * Fetches a student profile from Firestore based on the userId.
 * Assumes there's at most one student profile per userId.
 * @param db Firestore instance.
 * @param userId The UID of the user associated with the student profile.
 * @returns Promise<Student | null> The student profile or null if not found.
 */
export const getStudentProfileByUserId = async (
  db: Firestore,
  userId: string
): Promise<Student | null> => {
  const studentsCollection = collection(db, 'students');
  const q = query(studentsCollection, where('userId', '==', userId));
  const querySnapshot = await getDocs(q);

  if (!querySnapshot.empty) {
    // Assuming only one profile per userId
    const docSnap = querySnapshot.docs[0];
    return { id: docSnap.id, ...docSnap.data() } as Student;
  }
  return null;
};

/**
 * Updates an existing student profile in Firestore.
 * @param db Firestore instance.
 * @param studentProfileId The document ID of the student profile to update.
 * @param updates Partial data of Student to update. Excludes 'id', 'userId', 'createdAt'.
 * @returns Promise<void>
 */
export const updateStudentProfile = async (
  db: Firestore,
  studentProfileId: string,
  updates: Partial<Pick<Student, 'groupId' | 'enrollmentDate' | 'status' | 'studentCardId'>>
): Promise<void> => {
  const studentRef = doc(db, 'students', studentProfileId);
  const dataWithTimestamp = {
    ...updates,
    // Ensure enrollmentDate is a Timestamp if being updated
    updatedAt: serverTimestamp() as Timestamp,
  };
  return updateDoc(studentRef, dataWithTimestamp);
};

/**
 * Deletes a student profile from Firestore.
 * Note: This function does NOT update the corresponding User document's studentId.
 * That logic should be handled by the calling function, potentially using a batch write.
 * @param db Firestore instance.
 * @param studentProfileId The document ID of the student profile to delete.
 * @returns Promise<void>
 */
export const deleteStudentProfileInService = async (
  db: Firestore,
  studentProfileId: string
): Promise<void> => {
  const studentRef = doc(db, 'students', studentProfileId);
  return deleteDoc(studentRef);
};

/**
 * Fetches all student profiles from Firestore.
 * @param db Firestore instance.
 * @returns Promise<Student[]> An array of student profiles.
 */
export const getAllStudents = async (db: Firestore): Promise<Student[]> => {
  const studentsCollection = collection(db, 'students');
  const q = query(studentsCollection, orderBy('createdAt', 'desc')); // Optional: order by creation
  const querySnapshot = await getDocs(q);
  return querySnapshot.docs.map(docSnap => ({
    id: docSnap.id,
    ...docSnap.data(),
  } as Student));
};
